apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-1
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend
          image: 529646246979.dkr.ecr.ap-southeast-2.amazonaws.com/awstodo-backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: todoapp-secret
            - configMapRef:
                name: todoapp-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: todoapp
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
