all:
  children:
    k8s_master:
      hosts:
        master:
          ansible_host: 192.168.241.10
          ansible_user: yance
          ansible_ssh_private_key_file: ~/.ssh/k8s_master
          ansible_python_interpreter: /usr/bin/python3
